### ISSUE TITLE
I get this error while trying to run the example main.cpp in VS 2022 and/or executing the built .exe

### ISSUE THREAD

**Issue by Foxxey** [mlomb/flexui#3]
Active code page: 65001
Renderer: GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL version supported 4.6.0 NVIDIA 457.49
[FATAL] ---------------------
[FATAL] ASSERTION FAILED!
[FATAL] File: C:\Users\anton\source\repos\flexui\src\flexui\Misc\String.cpp
[FATAL] Line: 35
[FATAL] Function: flexui::StringSection::section
[FATAL] Condition: (start <= end)
[FATAL] Details: "-"
[FATAL] ---------------------

C:\Users\anton\source\repos\flexui\out\build\x64-Debug\examples\glfw_gl3\glfw_gl3.exe (process 1536) exited with code -2147483645.
Press any key to close this window . . .

**Comment by mlomb** [comment]
It seems that when the CSS parser encounters whitespace at the end it breaks. I removed the whitespace in the example.

Note that you may not see any output, the main branch is currently broken IIRC.

**Comment by Foxxey** [comment]
do you have a working example you can provide?

**Comment by mlomb** [comment]
Try the last commit that passed CI:

[dff1fd08fb0cfcdcdd7e513041fd93decee4a3ae](https://github.com/mlomb/flexui/commit/dff1fd08fb0cfcdcdd7e513041fd93decee4a3ae)

[Web demo](https://mlomb.github.io/flexui/)
